version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing pip dependencies"
      - pip install --upgrade pip
      - echo "Logging in to CodeArtifact"
      - aws codeartifact login --tool pip --repository todolist-devops-cicd --domain todolist --domain-owner 247487031027 --region ap-south-1
      - echo "Installing requirements"
      - pip install -r backend/requirements.txt

  pre_build:
    commands:
      - echo "Downloading .env file from S3"
      - aws s3 cp s3://todolist-devops-cicd/todolist/.env .env || echo ".env file not found in S3"
      - echo "Running Django migrations"
      - cd backend
      - python3 manage.py makemigrations || echo "No new migrations to apply"
      - python3 manage.py migrate
      - cd ..

  build:
    commands:
      - echo "Collecting static files"
      - cd backend
      - python3 manage.py collectstatic --noinput || echo "No static files to collect"
      - cd ..
      - echo "Making shell scripts executable"
      - chmod +x scripts/*.sh
      - echo "Copying files to packaged-output directory"
      - mkdir -p packaged-output
      - cp -r backend scripts appspec.yml .env packaged-output/
      - echo "Listing packaged-output contents"
      - ls -l packaged-output
      - echo "Creating zip file"
      - cd packaged-output
      - zip -r ../todolist.zip .
      - cd ..

artifacts:
  files:
    - todolist.zip