version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing pip dependencies"
      - pip install --upgrade pip
      - echo "Logging in to CodeArtifact"
      - aws codeartifact login --tool pip --repository todolist-devops-cicd --domain todolist --domain-owner 247487031027 --region ap-south-1
      - echo "Installing requirements"
      - pip install -r backend/requirements.txt

  pre_build:
    commands:
      - echo "Downloading .env file from S3"
      - aws s3 cp s3://todolist-devops-cicd/todolist/.env .env || echo ".env file not found in S3"
      - echo 'SKIP_DB is set to: $(grep SKIP_DB backend/todolist/.env || echo "NOT FOUND")'
      - echo "Running Django migrations"
      - cd backend
      - python3 manage.py makemigrations || echo "No new migrations to apply"
      - python3 manage.py migrate

  build:
    commands:
      - echo "Collecting static files"
      - python3 manage.py collectstatic --noinput || echo "No static files to collect"

  post_build:
    commands:
      - echo "Build completed at $(date)"

artifacts:
  files:
    - "**/*"
  discard-paths: no