# Generated by Django 5.1.7 on 2025-03-29 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
